# Generated by Django 3.0.14 on 2021-12-14 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_details', models.CharField(blank=True, max_length=255)),
                ('station_id', models.CharField(blank=True, db_index=True, help_text='Wewnętrzny identyfikator stacji operatora', max_length=16, verbose_name='StationId')),
                ('rnc', models.PositiveSmallIntegerField(default=0, help_text='Radio Network Controller (dla stacji UMTS)', verbose_name='RNC')),
                ('enbi', models.PositiveIntegerField(default=0, help_text='eNodeB ID (dla stacji LTE)', verbose_name='eNBID')),
                ('is_common_bcch', models.BooleanField(default=False)),
                ('is_gsm', models.BooleanField(default=False)),
                ('is_umts', models.BooleanField(default=False)),
                ('is_cdma', models.BooleanField(default=False)),
                ('is_lte', models.BooleanField(default=False)),
                ('is_networks', models.BooleanField(db_index=True, default=False, verbose_name='Is NetWorks!')),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('station_status', models.CharField(choices=[('OnAir', 'OnAir'), ('Offline', 'Offline'), ('UnderConstruction', 'UnderConstruction'), ('Planned', 'Planned'), ('Dismantled', 'Dismantled')], max_length=32)),
                ('edit_status', models.CharField(choices=[('Published', 'Published'), ('Approved', 'Approved'), ('Queued', 'Queued'), ('Rejected', 'Rejected')], max_length=32)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('code', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('operator_name', models.CharField(max_length=128)),
                ('country_code', models.CharField(max_length=2)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('code', models.CharField(max_length=3)),
                ('country_code', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=512)),
                ('latitude', models.DecimalField(db_index=True, decimal_places=6, max_digits=8)),
                ('longitude', models.DecimalField(db_index=True, decimal_places=6, max_digits=8)),
                ('location_hash', models.CharField(db_index=True, max_length=32)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='bts.Region')),
            ],
            options={
                'ordering': ['town'],
            },
        ),
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard', models.CharField(choices=[('GSM', 'GSM'), ('UMTS', 'UMTS'), ('CDMA', 'CDMA'), ('LTE', 'LTE'), ('5G', '5G'), ('IOT', 'IOT')], db_index=True, max_length=8)),
                ('band', models.CharField(choices=[('420', '420'), ('450', '450'), ('800', '800'), ('850', '850'), ('900', '900'), ('1800', '1800'), ('2100', '2100'), ('2600', '2600')], db_index=True, max_length=8)),
                ('ua_freq', models.PositiveSmallIntegerField(blank=True, default=0, help_text='Częstotliwość nośnej (kanał RF)', verbose_name='UaFreq')),
                ('lac', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='LAC')),
                ('cid', models.PositiveSmallIntegerField(blank=True, default=0, help_text='CellID / Cell Local ID (uniwersalny)', verbose_name='CID/CLID')),
                ('cid_long', models.PositiveIntegerField(blank=True, default=0, help_text='UMTS: RNC*65536+CID; LTE: eNBID*256+CLID', verbose_name='Long CID/E-CID')),
                ('azimuth', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_confirmed', models.BooleanField(verbose_name='Confirmed?')),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('date_ping', models.DateTimeField(blank=True, null=True)),
                ('base_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='bts.BaseStation')),
            ],
        ),
        migrations.CreateModel(
            name='BaseStationPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(db_index=True, max_length=16, verbose_name='StationId')),
                ('base_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='bts.BaseStation', verbose_name='Base station')),
            ],
        ),
        migrations.AddField(
            model_name='basestation',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_stations', to='bts.Location'),
        ),
        migrations.AddField(
            model_name='basestation',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_stations', to='bts.Network'),
        ),
    ]
