# Generated by Django 3.0.14 on 2021-12-14 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uke', '0001_initial'),
        ('bts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basestationpermission',
            name='permission',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='base_stations', to='uke.Permission', verbose_name='UKE Permission'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='basestationpermission',
            unique_together={('base_station', 'permission', 'station_id')},
        ),
    ]
