# Generated by Django 3.0.14 on 2021-12-14 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(db_index=True, decimal_places=6, max_digits=8)),
                ('longitude', models.DecimalField(db_index=True, decimal_places=6, max_digits=8)),
                ('latitude_uke', models.CharField(max_length=16)),
                ('longitude_uke', models.CharField(max_length=16)),
                ('location_hash', models.CharField(db_index=True, max_length=32, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RawRecord',
            fields=[
                ('operator_name', models.CharField(max_length=200)),
                ('case_number', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('case_number_orig', models.CharField(max_length=64)),
                ('case_type', models.CharField(max_length=16)),
                ('expiry_date', models.CharField(max_length=10)),
                ('longitude', models.CharField(max_length=16)),
                ('latitude', models.CharField(max_length=16)),
                ('town', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('station_id', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(db_index=True, max_length=16)),
                ('standard', models.CharField(db_index=True, max_length=16)),
                ('band', models.CharField(db_index=True, max_length=16)),
                ('town', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('case_number', models.CharField(db_index=True, max_length=64, unique=True)),
                ('case_number_orig', models.CharField(max_length=64)),
                ('case_type', models.CharField(max_length=16)),
                ('expiry_date', models.CharField(max_length=10)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='uke.Location')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='uke.Operator')),
            ],
        ),
    ]
