# Generated by Django 3.0.14 on 2021-12-14 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bts', '0002_auto_20211215_0058'),
        ('uke', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='network',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='uke_operators', to='bts.Network'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='permission',
            name='network',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='bts.Network'),
        ),
    ]
